Fix two small visual bugs
sdenec/tidy5e-sheet pull request #134
Opened 2020-11-11 22:00 UTC by etnbrd

When using this, I found that the item lines in the inventory where displayed with an unnecessary margin on the h4 title resulting in a broken display.
Also displaying the delete icon as `block` makes it appear an a new line, breaking the inventory item line as well. Displaying it as `inline` makes it appear beside its siblings.

These are just some fixes from my observations. Maybe they only appear in my specific case and would break things for others. I am just sharing this to help you maintain this module.

2020-11-11 22:21 UTC, sdenec requested changes
The css behaves as it should, the sheet does not diplay any styling errors in the changed blocks. The "h4" already inherits "margin: 0" from the default sheet css. The delete buttons should be "display: block" as they are in a flex element - "inline" would not change the display behaviour.

2020-11-12 11:47 UTC, etnbrd commented
From what I see, the h4 doesn't inherit `margin: 0` but `margin: 0 0 0.5rem` from the main foundry stylesheet (cf. screenshot below)
We are on version 0.7.6, and maybe the discrepancies in inherited styles come from a difference of version?

<img width="1201" alt="Screenshot 2020-11-12 at 12 25 36 PM" src="https://user-images.githubusercontent.com/5691124/98934370-442de780-24e2-11eb-8364-e0104380bf4d.png">

For the delete icon, you are entirely right.
Though, from what I see, it doesn't get the `display: flex` it should, so I added it where I think it should go (but I might be wrong).

2020-11-12 14:24 UTC, sdenec commented
Your sheet is completely botched. Are you sure you are on dnd5e version 1.1.1? This suspiciously looks like an old game system as you also are missing the "effects" tab. All those error where corrected in the sheet.

2020-11-12 14:30 UTC, etnbrd commented
Ah, indeed, no we were still on 0.99 🤦 Thanks a lot and sorry for the noise.

2020-11-12 14:30 UTC, closed without merging